### ISSUE TITLE
Is there more guidance documentation to help?

### ISSUE THREAD

**Issue by ulysses936** [Beckhoff-USA-Community/PackML_PLC_Example#8]
Are there any more guide documents to help us use this framework?
For example, where we should modify and where we should not, and how to use templates step by step to build an EM.
In addition, I encountered a little problem when reading PDF and using the framework:

1. It seems that the new version of the framework uses registersubmodules() and registercomponects() to initialize submodules and components. At this time, can the FOR loop, ipSubmodules_Init and ipComponents_Init arrays in the original EM initialization method be deleted, and can both initialization methods be written? What's the difference? Which recommend?

2. In the new version of the framework, the initialization code in the FB_EquipmentModuleTemplata uses the identifier SPT_PackMLBase of the old library. If the new version also uses FOR loop to initialize, it seems that it should be changed.

3. Where should I get the Excel Addin mentioned in the PDF?

**Comment by MarkLewis-Beckhoff** [comment]
I will address these in reverse order.
3.  The Addin is something you would need to request from your local Beckhoff office and be prepared that they may not be able to provide it as it is an "unsupported utility". 
2. Our team methodology for the registration of both submodule and components has changed to the way that the latest update to the sample program shows, the libraries have not changed to preserve backward compatibility until the release of version 4 of the libraries which will be a known breaking change release.
1. both methods remain functional the updated sample simply reflects some best practices and lessons learned during the implementation of larger projects. we have simply exposed the registration method which was called in the FOR loop and allowed for the direct calling of it in order to register things in a specific order and to be able to troubleshoot in the event of a module not completing its initialization.

The documentation which I think you have already found is here: https://beckhoff-usa-community.github.io/SPT-Libraries/Getting_Started/setup.html and we recently added some of the beginning videos of a larger series.

**Comment by ulysses936** [comment]
Thank you for your reply! After few days using this frameword on a brand new project where partyA requests to include PackML statemachine and other features , I am becoming more familiar with your framework. Thanks to your efforts, this framework is currently very good to use.
At present, there is another question. I am not sure if a new issue needs to be opened to ask, as it is a different question. 

Our partyA wants to make  a 'decoupling function'. When one of my EMs encounters a problem, I can separate it from the entire Machine. The error of that EM will not affect the machine, and the machine's statemachine will no longer be effective for that EM (so the machine will not get stuck when checking submaodulesareallready).

The issue of alarms can be easily solved by setting the parent...definition array, but the problem of state machines seems to be a bit more complex. The issuance and detection of the state machine are written in the base. One method is that I can rewrite the detection method and add a variable to EM. If the variable is true, the statemachine will not be issued and the ready signal will not include this EM. Another method is to write an unregister method to delete and reorder the EMs in ipsubModules (not during runtime).

From your professional perspective, can these methods work and is there any better ways to make it?

Finally, by the way, am I allowed to translate the tutorial page you mentioned into other languages and share it with others or other website? (Source will be indicated)

**Comment by runtimevic** [comment]
> I will address these in reverse order. 3. The Addin is something you would need to request from your local Beckhoff office and be prepared that they may not be able to provide it as it is an "unsupported utility". 2. Our team methodology for the registration of both submodule and components has changed to the way that the latest update to the sample program shows, the libraries have not changed to preserve backward compatibility until the release of version 4 of the libraries which will be a known breaking change release.
> 
> 1. both methods remain functional the updated sample simply reflects some best practices and lessons learned during the implementation of larger projects. we have simply exposed the registration method which was called in the FOR loop and allowed for the direct calling of it in order to register things in a specific order and to be able to troubleshoot in the event of a module not completing its initialization.
> 
> The documentation which I think you have already found is here: https://beckhoff-usa-community.github.io/SPT-Libraries/Getting_Started/setup.html and we recently added some of the beginning videos of a larger series.

Hello @MarkLewis-Beckhoff ,
What does the version 4 mean?, changes are coming that break the previous?
thanks, Víctor.

**Comment by dmolley** [comment]
I am diving into the SPT framework and the VFFS demo program. Good work!
However I think it needs more details in the documentation to be fully useful.
Or perhaps I am not finding all of the docs.
For example, where is the FB_Tree_IndexBase.AddNodeAsChildByName used? What is it for?
Rather than just listing the methods and properties in the docs, more detail would be helpful, like why this method is useful (its purpose?), where it is used and/or how would we use it 
It would also be nice to know what to expect from the VFFS demo app. What should we expect when it is run?
Is a visual element supposed to pop up? How do we test it? 
There seem to be little or no details on the operation of the VFFS Demo program.

**Comment by MarkLewis-Beckhoff** [comment]
Hello, thank you for taking a look.
so there are several places to pick up information. operationally there should be a .pdf in the repo itself.
from the visual side there are 2 places as there are 2 ways to handle this. 
1. there is a PLC visualization in the project itself.
2. there is an actual TwinCAT HMI Project that is connected located here https://github.com/Beckhoff-USA-Community/PackML_HMI_Example 
both will need to be manually started to be used.
as to more information basic library documentation that can be found here https://beckhoff-usa-community.github.io/SPT-Libraries/
as to the FB in question it is an artifact from an earlier version which remains simply to not break projects written using the earlier library releases.
